// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiejemplo.Data;

#nullable disable

namespace WebApiejemplo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250407225146_SEXTA")]
    partial class SEXTA
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiejemplo.Models.Cliente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("NIT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOMBRE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CLIENTE", "EVMNET");
                });

            modelBuilder.Entity("WebApiejemplo.Models.Empresa", b =>
                {
                    b.Property<int>("IDEMPRESA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDEMPRESA"));

                    b.Property<string>("NOMBREEMPRESA")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDEMPRESA");

                    b.ToTable("EMPRESA", "EVMNET");
                });
#pragma warning restore 612, 618
        }
    }
}
