// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiejemplo.Data;

#nullable disable

namespace WebApiejemplo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260420180934_inita")]
    partial class inita
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiejemplo.Models.Apartamentos", b =>
                {
                    b.Property<int>("UnidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnidadId"));

                    b.Property<decimal?>("Area")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("TorreId")
                        .HasColumnType("int");

                    b.HasKey("UnidadId");

                    b.HasIndex("TorreId");

                    b.ToTable("Apartamentos");
                });

            modelBuilder.Entity("WebApiejemplo.Models.BitacoraVigilancia", b =>
                {
                    b.Property<int>("BitacoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BitacoraId"));

                    b.Property<DateTime>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("VigilanteId")
                        .HasColumnType("int");

                    b.HasKey("BitacoraId");

                    b.HasIndex("VigilanteId");

                    b.ToTable("BitacoraVigilancia");
                });

            modelBuilder.Entity("WebApiejemplo.Models.Conjunto", b =>
                {
                    b.Property<int>("ConjuntoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConjuntoId"));

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NIT")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ConjuntoId");

                    b.ToTable("Conjunto");
                });

            modelBuilder.Entity("WebApiejemplo.Models.Ingreso", b =>
                {
                    b.Property<int>("IngresoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngresoId"));

                    b.Property<string>("Documento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaHoraIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaHoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombrePersona")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("UnidadId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("IngresoId");

                    b.HasIndex("UnidadId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ingreso");
                });

            modelBuilder.Entity("WebApiejemplo.Models.Mantenimiento", b =>
                {
                    b.Property<int>("MantenimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MantenimientoId"));

                    b.Property<decimal?>("Costo")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Estado")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Proveedor")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TipoMantenimientoId")
                        .HasColumnType("int");

                    b.Property<int?>("ZonaComunId")
                        .HasColumnType("int");

                    b.HasKey("MantenimientoId");

                    b.HasIndex("TipoMantenimientoId");

                    b.HasIndex("ZonaComunId");

                    b.ToTable("Mantenimiento");
                });

            modelBuilder.Entity("WebApiejemplo.Models.Mensajeria", b =>
                {
                    b.Property<int>("MensajeriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MensajeriaId"));

                    b.Property<string>("Empresa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRecepcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Guia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UnidadId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("MensajeriaId");

                    b.HasIndex("UnidadId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Mensajeria");
                });

            modelBuilder.Entity("WebApiejemplo.Models.Parqueadero", b =>
                {
                    b.Property<int>("ParqueaderoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParqueaderoId"));

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UnidadId")
                        .HasColumnType("int");

                    b.HasKey("ParqueaderoId");

                    b.HasIndex("UnidadId");

                    b.ToTable("Parqueadero");
                });

            modelBuilder.Entity("WebApiejemplo.Models.ParqueaderoVisitante", b =>
                {
                    b.Property<int>("ParqueaderoVisitanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParqueaderoVisitanteId"));

                    b.Property<DateTime>("FechaHoraIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaHoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IngresoId")
                        .HasColumnType("int");

                    b.Property<int>("ParqueaderoId")
                        .HasColumnType("int");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ParqueaderoVisitanteId");

                    b.HasIndex("IngresoId");

                    b.HasIndex("ParqueaderoId");

                    b.ToTable("ParqueaderoVisitante");
                });

            modelBuilder.Entity("WebApiejemplo.Models.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("ZonaComunId")
                        .HasColumnType("int");

                    b.HasKey("ReservaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ZonaComunId");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("WebApiejemplo.Models.ResidenteUnidad", b =>
                {
                    b.Property<int>("ResidenteUnidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResidenteUnidadId"));

                    b.Property<bool>("EsPropietario")
                        .HasColumnType("bit");

                    b.Property<int>("UnidadId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ResidenteUnidadId");

                    b.HasIndex("UnidadId");

                    b.HasIndex("UsuarioId", "UnidadId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Residente_Unidad");

                    b.ToTable("ResidenteUnidad");
                });

            modelBuilder.Entity("WebApiejemplo.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolId");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_Rol_Nombre");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("WebApiejemplo.Models.TipoMantenimiento", b =>
                {
                    b.Property<int>("TipoMantenimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoMantenimientoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TipoMantenimientoId");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_TipoMantenimiento_Nombre");

                    b.ToTable("TipoMantenimiento");
                });

            modelBuilder.Entity("WebApiejemplo.Models.Torre", b =>
                {
                    b.Property<int>("TorreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TorreId"));

                    b.Property<int>("ConjuntoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TorreId");

                    b.HasIndex("ConjuntoId");

                    b.ToTable("Torre");
                });

            modelBuilder.Entity("WebApiejemplo.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("RolId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("WebApiejemplo.Models.ZonaComun", b =>
                {
                    b.Property<int>("ZonaComunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZonaComunId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequierePago")
                        .HasColumnType("bit");

                    b.Property<decimal?>("ValorHora")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ZonaComunId");

                    b.ToTable("ZonaComun");
                });

            modelBuilder.Entity("WebApiejemplo.Models.Apartamentos", b =>
                {
                    b.HasOne("WebApiejemplo.Models.Torre", "Torre")
                        .WithMany()
                        .HasForeignKey("TorreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Torre");
                });

            modelBuilder.Entity("WebApiejemplo.Models.BitacoraVigilancia", b =>
                {
                    b.HasOne("WebApiejemplo.Models.Usuario", "Vigilante")
                        .WithMany()
                        .HasForeignKey("VigilanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vigilante");
                });

            modelBuilder.Entity("WebApiejemplo.Models.Ingreso", b =>
                {
                    b.HasOne("WebApiejemplo.Models.Apartamentos", "Unidad")
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebApiejemplo.Models.Usuario", "Vigilante")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unidad");

                    b.Navigation("Vigilante");
                });

            modelBuilder.Entity("WebApiejemplo.Models.Mantenimiento", b =>
                {
                    b.HasOne("WebApiejemplo.Models.TipoMantenimiento", "TipoMantenimiento")
                        .WithMany()
                        .HasForeignKey("TipoMantenimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiejemplo.Models.ZonaComun", "ZonaComun")
                        .WithMany()
                        .HasForeignKey("ZonaComunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TipoMantenimiento");

                    b.Navigation("ZonaComun");
                });

            modelBuilder.Entity("WebApiejemplo.Models.Mensajeria", b =>
                {
                    b.HasOne("WebApiejemplo.Models.Apartamentos", "Unidad")
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiejemplo.Models.Usuario", "Vigilante")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unidad");

                    b.Navigation("Vigilante");
                });

            modelBuilder.Entity("WebApiejemplo.Models.Parqueadero", b =>
                {
                    b.HasOne("WebApiejemplo.Models.Apartamentos", "Unidad")
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("WebApiejemplo.Models.ParqueaderoVisitante", b =>
                {
                    b.HasOne("WebApiejemplo.Models.Ingreso", "Ingreso")
                        .WithMany()
                        .HasForeignKey("IngresoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebApiejemplo.Models.Parqueadero", "Parqueadero")
                        .WithMany()
                        .HasForeignKey("ParqueaderoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ingreso");

                    b.Navigation("Parqueadero");
                });

            modelBuilder.Entity("WebApiejemplo.Models.Reserva", b =>
                {
                    b.HasOne("WebApiejemplo.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiejemplo.Models.ZonaComun", "ZonaComun")
                        .WithMany()
                        .HasForeignKey("ZonaComunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("ZonaComun");
                });

            modelBuilder.Entity("WebApiejemplo.Models.ResidenteUnidad", b =>
                {
                    b.HasOne("WebApiejemplo.Models.Apartamentos", "Unidad")
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiejemplo.Models.Usuario", "Usuario")
                        .WithMany("ResidentesUnidad")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unidad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebApiejemplo.Models.Torre", b =>
                {
                    b.HasOne("WebApiejemplo.Models.Conjunto", "Conjunto")
                        .WithMany()
                        .HasForeignKey("ConjuntoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conjunto");
                });

            modelBuilder.Entity("WebApiejemplo.Models.Usuario", b =>
                {
                    b.HasOne("WebApiejemplo.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("WebApiejemplo.Models.Usuario", b =>
                {
                    b.Navigation("ResidentesUnidad");
                });
#pragma warning restore 612, 618
        }
    }
}
